export { default as Template } from './Template/Template';
export { default as Login } from './Auth/Login';
export { default as Register } from './Auth/Register';
export { default as Home } from './Home/Home';
export { default as Dashboard } from './Dashboard/Dashboard';
export { default as Resources } from './Resources/Resources';
export { default as Contact } from './Contact/Contact';
export { default as About } from './About/About';
export { default as Templates } from './Templates/Templates';
